# Generated by Django 5.0 on 2023-12-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, unique=True)),
                ('penulis', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('tanggal_terbit', models.DateField()),
            ],
        ),
    ]
