# Generated by Django 5.0 on 2023-12-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
